# Use base image
FROM ubuntu:20.04

# Avoid user input prompts during install
ENV DEBIAN_FRONTEND=noninteractive

# Install nginx
RUN apt update && apt install -y nginx

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

